export const Users = [
  {
    id: 1,
    profilePicture: "person/norm.jpeg",
    username: "Norm",
  },
  {
    id: 2,
    profilePicture: "person/norm.jpeg",
    username: "Holden Caulfield",
  },
  {
    id: 3,
    profilePicture: "person/norm.jpeg",
    username: "Aldous Huxley",
  },
  {
    id: 4,
    profilePicture: "person/norm.jpeg",
    username: "Dutch Vanderlinde",
  },
  {
    id: 5,
    profilePicture: "person/norm.jpeg",
    username: "Hosea Matthews",
  },
  {
    id: 6,
    profilePicture: "person/norm.jpeg",
    username: "Abigail Marston",
  },
  {
    id: 7,
    profilePicture: "person/norm.jpeg",
    username: "Sadie Adler",
  },
  {
    id: 8,
    profilePicture: "person/norm.jpeg",
    username: "Tommy Vercetti",
  },
  {
    id: 9,
    profilePicture: "person/norm.jpeg",
    username: "Booker Dewitt",
  },
  {
    id: 10,
    profilePicture: "person/norm.jpeg",
    username: "Old Man River",
  },
];

export const Posts = [
  {
    id: 1,
    title: "And the moth says, “‘Cause the light was on.”",
    photo: "howl1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "arietty1.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    title: "Soma is a remedy for the forsaken",
    photo: "fall.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    title: "The fall of dreams",
    photo: "kaguya1.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    title: "Dust to blue sky to dust",
    photo: "space.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "arietty1.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    title: "Howling in castles",
    photo: "howl1.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "space.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    title: "As the Crow flies",
    photo: "kaguya1.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "howl1.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
